apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx.fullname" . }}
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
      listen 80;
      server_name _;

      location / {
        add_header Content-Type text/plain;
        return 200 {{ .Values.webContent | quote }};
      }
    }
